language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: extremely-cool-app
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: ip7LyXqCm9KkDKdqWzBMEreuH/FiZZkMk/bdqQYrU8W8+rbE6zPuVv3utRS5BFCMysfyF9hOuzhJK27FJuHgIo1ONazcUgSe4tVo/0tMSozAuM2hPhPIVasDKvQO0t43nniUg6367p1laOM7syNwWwmhK0sO+wHlVU/TIECOSusENgfC3PT1Q1USjNlO7FDEt8NNt5hNoLRzaQxBDjs5QFjCwN5zsl98l9OpgWP2QpuSQjPmhgXTJDMV77E+b2sMwN22DfVGXgZgA8XO3EpoTCnUamxp0arf0FihpY69PdhiU8nMXnhS439Mr4AtwNkslAfRAuv0QpEOT2mq09xoY5LMybWFHk5SdXRhvoQ1sTZpFi8q46ltT5KdS+tepOW2nSj5uwjehSpDjIpV9qd9zhtTb3996jG8053NhMl5xtrgqejnZG+kP481ckGApn3Yq77UhwrYrVFTa+pMkj3bJmCq+BDG+ceHFS/6btxy8kp+plNEyjYq/l15sdHgzxhgAIpVaLhThUOF7xYa1Bkquwr7gVluCvGwYQplzlfg+wVcDsaKlkdXw6VyYJUZXHgo3WuHoapRV842hG3xIl0zGhq3/3V5uZLGoqVulld2r1qHhktRbaNF+RbVy260lkyjOUQlfqK9cV1eXl1uGdmO4qm9NLidPeKyBFFXZMVJzb4=
